got certbot going

diff --git a/install-unit b/install-unit
--- a/install-unit
+++ b/install-unit
@@ -1,16 +1,14 @@
 #!/bin/bash
 # Crude install script for nginx-unit and a python3 module to /opt/unit
 #
-# Note that I had the following dependencies already:
-#  sudo apt install certbot ddclient python3-venv python3-dev build-essential libssl-dev libssl-doc libpcre2-dev
-#
-# Also note that if this fails, it leaves around the temporary build directory
+# Note that if this fails, it leaves around the temporary build directory.
 
 version=$1
 
 [ "$version" ] || {
   echo >&2 "usage: $0 VERSION"
-  echo >&2 "  i.e. $0 1.22.0"
+  echo >&2 "  - i.e. $0 1.22.0"
+  echo >&2 "  - see https://github.com/nginx/unit/releases for versions"
   exit 1
 }
 
@@ -19,7 +17,7 @@ version=$1
   exit 1
 }
 
-set -exo pipefail
+set -exo pipefail  # bail on any error
 
 curl -L "https://github.com/nginx/unit/archive/$version.tar.gz" | tar -xzf -
 cd "unit-$version"
@@ -28,4 +26,6 @@ cd "unit-$version"
 make
 sudo make install
 cd ..
-rm -rf "unit-$version"
+rm -rf "unit-$version"  # cleanup temp directory
+
+sudo /opt/unit/sbin/unitd  # start unitd
